# Generated by Django 5.1.7 on 2025-03-27 10:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_post_rgq6aq', max_length=255, verbose_name='image'),
        ),
    ]
