# Generated by Django 4.2.20 on 2025-03-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_jww1ll', upload_to='images/'),
        ),
    ]
