# Generated by Django 5.1.7 on 2025-03-22 23:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_profile_pmyox9', max_length=255, verbose_name='image'),
        ),
    ]
